# Generated by Django 3.1.7 on 2021-03-13 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0024_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='pst_image3',
            field=models.FileField(blank=True, null=True, upload_to='uploads/', verbose_name='Single Room Image'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='pst_image4',
            field=models.FileField(blank=True, null=True, upload_to='uploads/', verbose_name='Double Room Image 1'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='pst_image5',
            field=models.FileField(blank=True, null=True, upload_to='uploads/', verbose_name='Suite Room Image 2'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.CharField(choices=[('one', '1'), ('two', '2'), ('three', '3'), ('four', '4'), ('five', '5'), ('', 'Choose Rating')], default='', max_length=15),
        ),
    ]
