# Generated by Django 3.1.7 on 2021-03-13 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0025_auto_20210313_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='rate',
            field=models.CharField(default=0.0, max_length=10, verbose_name='Rating'),
            preserve_default=False,
        ),
    ]
