# Generated by Django 3.1.7 on 2021-03-15 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0026_hotel_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='location_id',
        ),
        migrations.AddField(
            model_name='hotel',
            name='place',
            field=models.CharField(default='-------------', max_length=20, verbose_name='Location'),
            preserve_default=False,
        ),
    ]
