# Generated by Django 2.1.5 on 2021-04-10 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0028_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='price',
            field=models.CharField(choices=[('100,000', ' 100,000'), ('150,00', ' 150,000'), ('200,000', ' 200,000'), ('250,000', ' 250,000'), ('300,000', ' 300,000'), ('350,000', ' 350,000'), ('400,000', ' 400,000'), ('450,000', ' 450,000'), ('500,000', ' 500,000'), ('550,000', ' 550,000'), ('600,000', ' 600,000'), ('650,000', ' 650,000'), ('700,000', ' 700,000'), ('750,000', ' 750,000'), ('800,000', ' 800,000'), ('850,000', ' 850,000'), ('900,000', ' 900,000'), ('950,000', ' 950,000'), ('1 Million', ' 1 Million'), ('1.5 Million', ' 1.5 Million'), ('2 Million', ' 2 Million'), ('2.5 Million', ' 2.5 Million'), ('3 Million', ' 3 Million'), ('3.5 Million', ' 3.5 Million'), ('4 Million', ' 4 Million'), ('4.5 Million', ' 4.5 Million'), ('5 Million', ' 5 Million'), ('', 'Please Choose')], default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='rate',
            field=models.CharField(max_length=10, verbose_name='Hotel Status'),
        ),
    ]
