# Generated by Django 2.1.5 on 2021-04-12 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0030_auto_20210410_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='place',
            field=models.CharField(choices=[('10000', ' 10000'), ('15000', ' 15000'), ('20000', ' 20000'), ('25000', ' 25000'), ('30000', ' 30000'), ('35000', ' 35000'), ('40000', ' 40000'), ('45000', ' 45000'), ('50000', ' 50000'), ('55000', ' 55000'), ('60000', ' 60000'), ('65000', ' 65000'), ('70000', ' 70000'), ('75000', ' 75000'), ('80000', ' 80000'), ('85000', ' 85000'), ('90000', ' 90000'), ('95000', ' 95000'), ('100,000', ' 100000'), ('', 'Price')], default='', max_length=20, verbose_name='Location'),
        ),
    ]
