# Generated by Django 2.1.5 on 2021-04-12 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0031_auto_20210411_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='place',
            field=models.CharField(choices=[('Ajah', 'Ajah'), ('Agege', 'Agege'), ('Ikeja', 'Ikeja'), ('Lekki Phase 1', 'Lekki Phase 1'), ('Lekki Phase 2', 'Lekki Phase 2'), ('Ikoyi', 'Ikoyi'), ('Oshodi', 'Oshodi'), ('Magodo', 'Magodo'), ('Victoria Island', 'Victoria Island'), ('Oniru VI', 'Oniru VI'), ('Mowe', 'Mowe'), ('Ikorodu', 'Ikorodu'), ('Festac', 'Festac'), ('Ojodu', 'Ojodu'), ('Banana Island', 'Banana Island'), ('Maryland', 'Maryland'), ('Ogba', 'Ogba'), ('Barracks', 'Barracks'), ('', 'Location')], default='', max_length=20, verbose_name='Location'),
        ),
    ]
