# Generated by Django 2.1.5 on 2021-04-13 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0032_auto_20210411_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='cat_id',
            field=models.ManyToManyField(default='', to='frontend.Category', verbose_name='Category'),
        ),
    ]
