# Generated by Django 2.1.5 on 2021-04-13 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0033_auto_20210413_1129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='cat_id',
        ),
        migrations.AddField(
            model_name='hotel',
            name='cat_id',
            field=models.CharField(choices=[('Hotel', 'Hotel'), ('Single Room', ' Single Room'), ('Double Room', 'Double Room'), ('Suite Room', 'Suite Room'), ('', 'Type')], default='', max_length=40),
        ),
    ]
