# Generated by Django 2.1.5 on 2021-04-14 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0034_auto_20210413_1149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='cat_id',
        ),
        migrations.AddField(
            model_name='hotel',
            name='cat_id',
            field=models.ManyToManyField(to='frontend.Category', verbose_name='Category'),
        ),
    ]
