# Generated by Django 2.1.5 on 2021-04-14 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0036_auto_20210414_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='cat_id',
            field=models.CharField(choices=[('Hotel', 'Hotel'), ('Single Room', ' Single Room'), ('Double Room', 'Double Room'), ('Suite Room', 'Suite Room'), ('', 'Hotel Room')], default='', max_length=40),
        ),
    ]
